name: Require Checklist
on:
  pull_request:
    types: [opened, edited]
  issue_comment:
    types: [created, edited, deleted]
jobs:
  job1:
    runs-on: ubuntu-16.04
    steps:
      - uses: larsa4d/require-checklist-action@master
        with:
          requireChecklist: false # Set to true if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
